<?php
/**
 * Created by PhpStorm.
 * User: developer
 * Date: 10/15/2016
 * Time: 2:53 PM
 */
if (Yii::$app->user->identity->role == UserTypes::ADMIN) {

    $all_pending_inquiries = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->joinWith(['inquiryHead'])->all();
    $all_pending_inquiries_agent = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.customer_type' => CustomerTypes::AGENT])->joinWith(['inquiryHead'])->all();

    $all_pending_inquiries_agent_maldives = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.customer_type' => CustomerTypes::AGENT,'inquiry.destination'=>'maldives'])->joinWith(['inquiryHead'])->all();
    $all_pending_inquiries_agent_mauritius = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.customer_type' => CustomerTypes::AGENT,'inquiry.destination'=>'mauritius'])->joinWith(['inquiryHead'])->all();
    $all_pending_inquiries_customer = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.customer_type' => CustomerTypes::CUSTOMER])->joinWith(['inquiryHead'])->all();
    $all_pending_inquiries_customer_maldives = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.customer_type' => CustomerTypes::CUSTOMER,'inquiry.destination'=>'maldives'])->joinWith(['inquiryHead'])->all();
    $all_pending_inquiries_customer_mauritius = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.customer_type' => CustomerTypes::CUSTOMER,'inquiry.destination'=>'mauritius'])->joinWith(['inquiryHead'])->all();
    $hot_new_inquiries_agent = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::HOT_NEW_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::AGENT])->joinWith(['inquiryHead'])->all();
    $hot_new_inquiries_agent_maldives = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::HOT_NEW_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::AGENT,'inquiry.destination'=>'maldives'])->joinWith(['inquiryHead'])->all();
    $hot_new_inquiries_agent_mauritius = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::HOT_NEW_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::AGENT,'inquiry.destination'=>'mauritius'])->joinWith(['inquiryHead'])->all();
    $hot_new_inquiries_customer = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::HOT_NEW_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::CUSTOMER])->joinWith(['inquiryHead'])->all();
    $hot_new_inquiries_customer_maldives = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::HOT_NEW_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::CUSTOMER,'inquiry.destination'=>'maldives'])->joinWith(['inquiryHead'])->all();
    $hot_new_inquiries_customer_mauritius = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' =>InquiryPriorityTypes::HOT_NEW_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::CUSTOMER,'inquiry.destination'=>'mauritius'])->joinWith(['inquiryHead'])->all();
    $hot_old_inquiries_agent = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::HOT_OLD_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::AGENT])->joinWith(['inquiryHead'])->all();
    $hot_old_inquiries_agent_maldives = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::HOT_OLD_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::AGENT,'inquiry.destination'=>'maldives'])->joinWith(['inquiryHead'])->all();
    $hot_old_inquiries_agent_mauritius = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::HOT_OLD_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::AGENT,'inquiry.destination'=>'mauritius'])->joinWith(['inquiryHead'])->all();
    $hot_old_inquiries_customer = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::HOT_OLD_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::CUSTOMER])->joinWith(['inquiryHead'])->all();
    $hot_old_inquiries_customer_maldives = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::HOT_OLD_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::CUSTOMER,'inquiry.destination'=>'maldives'])->joinWith(['inquiryHead'])->all();
    $hot_old_inquiries_customer_mauritius = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::HOT_OLD_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::CUSTOMER,'inquiry.destination'=>'mauritius'])->joinWith(['inquiryHead'])->all();
    $general_new_inquiries_agent = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::GENERAL_NEW_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::AGENT])->joinWith(['inquiryHead'])->all();
    $general_new_inquiries_agent_maldives = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::GENERAL_NEW_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::AGENT,'inquiry.destination'=>'maldives'])->joinWith(['inquiryHead'])->all();
    $general_new_inquiries_agent_mauritius = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::GENERAL_NEW_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::AGENT,'inquiry.destination'=>'mauritius'])->joinWith(['inquiryHead'])->all();
    $general_new_inquiries_customer = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::GENERAL_NEW_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::CUSTOMER])->joinWith(['inquiryHead'])->all();
    $general_new_inquiries_customer_maldives = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::GENERAL_NEW_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::CUSTOMER,'inquiry.destination'=>'maldives'])->joinWith(['inquiryHead'])->all();
    $general_new_inquiries_customer_mauritius = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority'  => InquiryPriorityTypes::GENERAL_NEW_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::CUSTOMER,'inquiry.destination'=>'mauritius'])->joinWith(['inquiryHead'])->all();
    $general_old_inquiries_agent = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::GENERAL_OLD_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::AGENT])->joinWith(['inquiryHead'])->all();
    $general_old_inquiries_agent_maldives = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::GENERAL_OLD_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::AGENT,'inquiry.destination'=>'maldives'])->joinWith(['inquiryHead'])->all();
    $general_old_inquiries_agent_mauritius = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::GENERAL_OLD_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::AGENT,'inquiry.destination'=>'mauritius'])->joinWith(['inquiryHead'])->all();
    $general_old_inquiries_customer = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::GENERAL_OLD_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::CUSTOMER])->joinWith(['inquiryHead'])->all();
    $general_old_inquiries_customer_maldives = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::GENERAL_OLD_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::CUSTOMER,'inquiry.destination'=>'maldives'])->joinWith(['inquiryHead'])->all();
    $general_old_inquiries_customer_mauritius = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->andWhere(['inquiry.inquiry_priority' => InquiryPriorityTypes::GENERAL_OLD_CUSTOMER, 'inquiry.customer_type' => CustomerTypes::CUSTOMER,'inquiry.destination'=>'mauritius'])->joinWith(['inquiryHead'])->all();

    $pending_inquiries = Inquiry::find()->where(['IN', 'inquiry.status', [InquiryStatusTypes::IN_QUOTATION, InquiryStatusTypes::AMENDED]])->joinWith(['inquiryHead'])->limit(5)->all();
    $pending_inquiries_count = count($all_pending_inquiries);

    $completed_inquiries_agent = Inquiry::find()->where(['inquiry.status' => InquiryStatusTypes::COMPLETED, 'inquiry.customer_type' => CustomerTypes::AGENT])->all();
    $completed_inquiries_agent_maldives = Inquiry::find()->where(['inquiry.status' => InquiryStatusTypes::COMPLETED, 'inquiry.customer_type' => CustomerTypes::AGENT,'inquiry.destination'=>'maldives'])->all();
    $completed_inquiries_agent_mauritius = Inquiry::find()->where(['inquiry.status' => InquiryStatusTypes::COMPLETED, 'inquiry.customer_type' => CustomerTypes::AGENT,'inquiry.destination'=>'mauritius'])->all();
    $completed_inquiries_customer = Inquiry::find()->where(['inquiry.status' => InquiryStatusTypes::COMPLETED, 'inquiry.customer_type' => CustomerTypes::CUSTOMER])->all();
    $completed_inquiries_customer_maldives = Inquiry::find()->where(['inquiry.status' => InquiryStatusTypes::COMPLETED, 'inquiry.customer_type' => CustomerTypes::CUSTOMER,'inquiry.destination'=>'maldives'])->all();
    $completed_inquiries_customer_mauritius = Inquiry::find()->where(['inquiry.status' => InquiryStatusTypes::COMPLETED, 'inquiry.customer_type' => CustomerTypes::CUSTOMER,'inquiry.destination'=>'mauritius'])->all();
    $cancelled_inquiries_agent = Inquiry::find()->where(['inquiry.status' => InquiryStatusTypes::CANCELLED, 'inquiry.customer_type' => CustomerTypes::AGENT])->all();
    $cancelled_inquiries_agent_maldives = Inquiry::find()->where(['inquiry.status' => InquiryStatusTypes::CANCELLED, 'inquiry.customer_type' => CustomerTypes::AGENT,'inquiry.destination'=>'maldives'])->all();
    $cancelled_inquiries_agent_mauritius = Inquiry::find()->where(['inquiry.status' => InquiryStatusTypes::CANCELLED, 'inquiry.customer_type' => CustomerTypes::AGENT,'inquiry.destination'=>'mauritius'])->all();
    $cancelled_inquiries_customer = Inquiry::find()->where(['inquiry.status' => InquiryStatusTypes::CANCELLED, 'inquiry.customer_type' => CustomerTypes::CUSTOMER])->all();
    $cancelled_inquiries_customer_maldives = Inquiry::find()->where(['inquiry.status' => InquiryStatusTypes::CANCELLED, 'inquiry.customer_type' => CustomerTypes::CUSTOMER,'inquiry.destination'=>'maldives'])->all();
    $cancelled_inquiries_customer_mauritius = Inquiry::find()->where(['inquiry.status' => InquiryStatusTypes::CANCELLED, 'inquiry.customer_type' => CustomerTypes::CUSTOMER,'inquiry.destination'=>'mauritius'])->all();

    $today = strtotime('today');
    $all_todays_followups = Followup::find()->where(['inquiry.status' => InquiryStatusTypes::QUOTED])->andWhere(['=', 'followup.date', $today])->andWhere(['followup.is_followup' => 0])->joinWith(['inquiry.inquiryHead', 'inquiry'])->groupBy('inquiry.id')->all();
    $all_todays_followups_agent = Followup::find()->where(['inquiry.status' => InquiryStatusTypes::QUOTED, 'inquiry.customer_type' => CustomerTypes::AGENT])->andWhere(['=', 'followup.date', $today])->andWhere(['followup.is_followup' => 0])->joinWith(['inquiry.inquiryHead', 'inquiry'])->groupBy('inquiry.id')->all();
    $all_todays_followups_customer = Followup::find()->where(['inquiry.status' => InquiryStatusTypes::QUOTED, 'inquiry.customer_type' => CustomerTypes::CUSTOMER])->andWhere(['=', 'followup.date', $today])->andWhere(['followup.is_followup' => 0])->joinWith(['inquiry.inquiryHead', 'inquiry'])->groupBy('inquiry.id')->all();
    $pending_followups_agent = Followup::find()->where(['inquiry.status' => InquiryStatusTypes::QUOTED, 'inquiry.customer_type' => CustomerTypes::AGENT])->andWhere(['<=', 'followup.date', $today])->andWhere(['followup.is_followup' => 0])->joinWith(['inquiry'])->groupBy('inquiry.id')->all();
    $pending_followups_agent_maldives = Followup::find()->where(['inquiry.status' => InquiryStatusTypes::QUOTED, 'inquiry.customer_type' => CustomerTypes::AGENT,'inquiry.destination'=>'maldives'])->andWhere(['<=', 'followup.date', $today])->andWhere(['followup.is_followup' => 0])->joinWith(['inquiry'])->groupBy('inquiry.id')->all();
    $pending_followups_agent_mauritius = Followup::find()->where(['inquiry.status' => InquiryStatusTypes::QUOTED, 'inquiry.customer_type' => CustomerTypes::AGENT,'inquiry.destination'=>'mauritius'])->andWhere(['<=', 'followup.date', $today])->andWhere(['followup.is_followup' => 0])->joinWith(['inquiry'])->groupBy('inquiry.id')->all();
    $pending_followups_customer = Followup::find()->where(['inquiry.status' => InquiryStatusTypes::QUOTED, 'inquiry.customer_type' => CustomerTypes::CUSTOMER])->andWhere(['<=', 'followup.date', $today])->andWhere(['followup.is_followup' => 0])->joinWith(['inquiry'])->groupBy('inquiry.id')->all();
    $pending_followups_customer_maldives = Followup::find()->where(['inquiry.status' => InquiryStatusTypes::QUOTED, 'inquiry.customer_type' => CustomerTypes::CUSTOMER,'inquiry.destination'=>'maldives'])->andWhere(['<=', 'followup.date', $today])->andWhere(['followup.is_followup' => 0])->joinWith(['inquiry'])->groupBy('inquiry.id')->all();
    $pending_followups_customer_mauritius = Followup::find()->where(['inquiry.status' => InquiryStatusTypes::QUOTED, 'inquiry.customer_type' => CustomerTypes::CUSTOMER,'inquiry.destination'=>'mauritius'])->andWhere(['<=', 'followup.date', $today])->andWhere(['followup.is_followup' => 0])->joinWith(['inquiry'])->groupBy('inquiry.id')->all();

    $todays_followups_agent = Followup::find()->where(['inquiry.status' => InquiryStatusTypes::QUOTED, 'inquiry.customer_type' => CustomerTypes::AGENT])->andWhere(['=', 'followup.date', $today])->andWhere(['followup.is_followup' => 0])->joinWith(['inquiry.inquiryHead', 'inquiry'])->groupBy('inquiry.id')->all();
    $todays_followups_agent_maldives = Followup::find()->where(['inquiry.status' => InquiryStatusTypes::QUOTED, 'inquiry.customer_type' => CustomerTypes::AGENT,'inquiry.destination'=>'maldives'])->andWhere(['=', 'followup.date', $today])->andWhere(['followup.is_followup' => 0])->joinWith(['inquiry.inquiryHead', 'inquiry'])->groupBy('inquiry.id')->all();
    $todays_followups_agent_mauritius = Followup::find()->where(['inquiry.status' => InquiryStatusTypes::QUOTED, 'inquiry.customer_type' => CustomerTypes::AGENT,'inquiry.destination'=>'mauritius'])->andWhere(['=', 'followup.date', $today])->andWhere(['followup.is_followup' => 0])->joinWith(['inquiry.inquiryHead', 'inquiry'])->groupBy('inquiry.id')->all();
    $todays_followups_customer = Followup::find()->where(['inquiry.status' => InquiryStatusTypes::QUOTED, 'inquiry.customer_type' => CustomerTypes::CUSTOMER])->andWhere(['=', 'followup.date', $today])->andWhere(['followup.is_followup' => 0])->joinWith(['inquiry.inquiryHead', 'inquiry'])->groupBy('inquiry.id')->all();
    $todays_followups_customer_maldives = Followup::find()->where(['inquiry.status' => InquiryStatusTypes::QUOTED, 'inquiry.customer_type' => CustomerTypes::CUSTOMER,'inquiry.destination'=>'maldives'])->andWhere(['=', 'followup.date', $today])->andWhere(['followup.is_followup' => 0])->joinWith(['inquiry.inquiryHead', 'inquiry'])->groupBy('inquiry.id')->all();
    $todays_followups_customer_mauritius = Followup::find()->where(['inquiry.status' => InquiryStatusTypes::QUOTED, 'inquiry.customer_type' => CustomerTypes::CUSTOMER,'inquiry.destination'=>'mauritius'])->andWhere(['=', 'followup.date', $today])->andWhere(['followup.is_followup' => 0])->joinWith(['inquiry.inquiryHead', 'inquiry'])->groupBy('inquiry.id')->all();
    $todays_followups = Followup::find()->where(['inquiry.status' => InquiryStatusTypes::QUOTED])->andWhere(['=', 'followup.date', $today])->andWhere(['followup.is_followup' => 0])->limit(5)->joinWith(['inquiry.inquiryHead', 'inquiry'])->groupBy('inquiry.id')->all();
    $todays_followups_count = count($all_todays_followups);
}